### PR TITLE
Added 6 hour nap option for upcoming Heroku pricing change

### PR DESCRIPTION
**Pull request by txizzle**
This is an updated pull request for the previous one I closed. I have tested this version at www.txkaffeine.herokuapp.com

I added a simple input field for a 'bedtime' for the application, when the application will be whitelisted from pings for 6 hours. Feel free to customize the UI, I just thought it would be cool to have support for the upcoming August 15 change.

This is my first time contributing to an open source project, I hope this helps! Please let me know if you have any feedback or questions about my changes.

### CODE REVIEW

**Comment by txizzle** [comment]
You'll might have to change your GA key back, and change the Logger text in scheduler.rake to fit your specifications.

**Comment by romainbutteaud** [comment]
Hey, Thanks Ted for your contribution, I will have look by EOW.

**Comment by romainbutteaud** [comment]
Alright, I'm going to merge this since a lot of people are waiting for this. Thanks @txizzle, great job (Y)

**Comment by txizzle** [comment]
Quick fix - I realized the app has to sleep for 7 hours, not 6 hours. This is because the app takes 1 hour of no requests to go to sleep, and then it sleeps for 6 hours, for a total of 7. 

Please change lines 12-22 of scheduler.rake to:
            if (site.nap == nil or !site.nap)
                Rails.logger.info "site doesn't nap. ping #{c}/#{total} (#{site.id}) #{Time.now} #{url}"
                hydra.queue(Typhoeus::Request.new(url, followlocation: true))
            elsif (7.hours.ago.strftime('%H:%M') <= site.bedtime and Time.now.strftime('%H:%M') >= site.bedtime)
                Rails.logger.info "it's during the site's bedtime! not pinging #{c}/#{total} (#{site.id}) #{Time.now} #{url} #{site.bedtime}"
            elsif (site.bedtime[0..1].to_i >= 17 and (7.hours.ago.strftime('%H:%M') <= site.bedtime) and Time.now.strftime('%H:%M') <= ("0" + (site.bedtime[0..1].to_i - 18).to_s + site.bedtime[2..4]))
                Rails.logger.info "it's during the site's bedtime which is after 17:00! not pinging #{c}/#{total} (#{site.id}) #{Time.now} #{url} #{site.bedtime}"
            else
                Rails.logger.info "it's not during the site's sleeping peroid. ping #{c}/#{total} (#{site.id}) #{Time.now} #{url} #{site.bedtime}"
                hydra.queue(Typhoeus::Request.new(url, followlocation: true))
            end

Thanks! Let me know if this helps. I stopped getting Heroku emails after I implemented this on my own app.

**Pull request merged**
