### PR TITLE
Allow sites to be removed

### LINKED ISSUE #4: Being able to remove apps from the admin section

### PR DESCRIPTION
**Pull request by acrogenesis**
Fixes #4 
Using the url `kaffeine.herokuapp.com/decaf/:name` you can remove your app from kaffeine. I also update rails

### CODE REVIEW

**Comment by romainbutteaud** [comment]
Awesome! Thank you @acrogenesis! :) 
Now we would need some information on the front page to explain the user how to remove the app.

**Comment by acrogenesis** [comment]
@romainbutteaud ready, here is a preview of how it works:

**Comment by acrogenesis** [comment]
bump

**Comment by romainbutteaud** [comment]
Thanks @acrogenesis for your contribution. Since "decaf" will rarely be used I would rather put a link in the footer:
After "Thanks for sharing!", put a link "Decaf" that shows a nice modal with the input and the button to remove the app. What do you think?

**Comment by acrogenesis** [comment]
Seems great to me, I'll update the PR in a moment

**Comment by acrogenesis** [comment]
@romainbutteaud done

**Comment by malolans** [comment]
Is there a time line on when this pull request would be merged? I would like to remove my app from kaffeine.

Thanks!

**Comment by romainbutteaud** [comment]
@acrogenesis @malolans merging :+1:

**Comment by malolans** [comment]
Thanks!

**Pull request merged**
